#!/bin/sh
# autopkgtest check: run padme unit tests and ensure everything passes
# (C) 2015 Canonical Ltd.
# Author: Zygmunt Krynicki <zygmunt.krynicki@canonical.com> 

set -e

cd $AUTOPKGTEST_TMP
python3 -m unittest padme.tests 2>&1
echo "unit-tests: OK"
